# Generated by Django 2.0 on 2018-07-11 17:08

import aira2.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aira2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_language',
            field=models.CharField(choices=[('EN', 'English'), ('EL', 'Ελληνικά')], default=aira2.choices.EMAIL_LANGUAGE_CHOICES('English'), max_length=100),
        ),
    ]
