# Generated by Django 2.2.2 on 2019-09-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aira", "0022_latlon")]

    operations = [
        migrations.AddField(
            model_name="agrifield",
            name="soil_analysis",
            field=models.FileField(blank=True, upload_to=""),
        )
    ]
