# Generated by Django 2.2.7 on 2019-11-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("aira", "0025_max_allowed_depletion")]

    operations = [
        migrations.RenameField(model_name="profile", old_name="farmer", new_name="user")
    ]
