# Generated by Django 2.2.7 on 2020-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aira", "0026_rename_profile_farmer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="notification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "Daily"),
                    ("2D", "Every two days"),
                    ("3D", "Every three days"),
                    ("4D", "Every four days"),
                    ("5D", "Every five days"),
                    ("7D", "Weekly"),
                    ("10D", "Every ten days"),
                    ("30D", "Monthly"),
                ],
                default="",
                max_length=3,
            ),
        ),
    ]
