# Generated by Django 2.2.7 on 2020-03-13 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aira", "0027_profile_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agrifield",
            name="custom_max_allowed_depletion",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(0.99),
                    django.core.validators.MinValueValidator(0.0),
                ],
            ),
        ),
    ]
